export const racketBrands = [
  "Yonex",
  "Victor",
  "Li-Ning",
  "Gosen",
  "Mizuno",
  "Kawasaki",
  "Apacs",
  "Flypower",
  "Redson",
  "Kumpoo",
  "Carlton",
  "Babolat",
  "Wilson",
  "Head",
  "Dunlop",
  "Adidas",
  "Ashaway",
  "Felet",
  "Hundra",
  "ProKennex",
];

// A small list of very popular models to help users get started
export const popularRacketModels = [
  "Astrox 100 ZZ",
  "Astrox 99 Pro",
  "Astrox 88D Pro",
  "Astrox 88S Pro",
  "Astrox 77 Pro",
  "Nanoflare 1000 Z",
  "Nanoflare 800 Pro",
  "Nanoflare 700",
  "Arcsaber 11 Pro",
  "Arcsaber 7 Pro",
  "Duora Z-Strike",
  "Thruster F",
  "Thruster Ryuga",
  "Auraspeed 100X",
  "Auraspeed 90K",
  "DriveX 9X",
  "Tectonic 9",
  "Axforce 80",
  "Axforce 90 Max",
  "Halbertec 8000",
];
